'use strict';

const DEFAULT_BUDGET = 999;
const ORCHESTRATOR_TIER_BUDGET = 1200;

const WORD_BUDGETS = {
  run: ORCHESTRATOR_TIER_BUDGET,
  homolog: ORCHESTRATOR_TIER_BUDGET,
};

const RUN_FOOTPRINT_BUDGET = 25000;

module.exports = { WORD_BUDGETS, DEFAULT_BUDGET, RUN_FOOTPRINT_BUDGET };
